### ISSUE TITLE
Jayce1kk

### ISSUE THREAD

**Issue by Jayce1kk** [gyxxyg/TRACE#1]
请问Trace能在GPU环境训练吗

**Comment by gyxxyg** [comment]
应该是可以的，我们代码库是基于videollama2修改的，所以可以参考videollama2的环境。不过我没有a100，所以没有具体尝试过。

**Comment by Jayce1kk** [comment]
好的 感谢

**Comment by zinuoli** [comment]
@gyxxyg 感谢回复，请问可以提供compressed版本的数据集吗，我想尝试一下在a100上训练

**Comment by zinuoli** [comment]
好的感谢，祝好运~

**Comment by zinuoli** [comment]
不好意思再次打扰，方便问一下当时您做预训练大概需要多少存储空间吗？ 非常感谢@gyxxyg
