### ISSUE TITLE
How to reproduce the number on ActivityNet-DVC

### ISSUE THREAD

**Issue by WikiChao** [gyxxyg/TRACE#3]
您好，我想复现ActivityNet-DVC上的结果。我下载了trace-uni checkpoint，以及有完整的activitynet-caption 数据集和标注 （原数据集格式），请问如何跑evaluation呢？我尝试用了eval.sh里面的activitynet格式，以及修改了相关路径等，但是在model.generate函数中出错了。请问有没有相关的activitynet evaluation的代码提供呢？感谢

<img width="468" alt="image" src="https://github.com/user-attachments/assets/ed357540-e67d-46ee-b561-f0ce69d29cac" />

**Comment by gyxxyg** [comment]
直接用我们的测试脚本应该可以复现，hf上有提供[eval的json file](https://huggingface.co/datasets/Yongxin-Guo/TRACE/tree/main/eval/dvc/anet)。如果遇到指标很奇怪可以再提供点细节给我

**Comment by gyxxyg** [comment]
麻烦把报错发一下给我，谢谢

**Comment by WikiChao** [comment]
> 直接用我们的测试脚本应该可以复现，hf上有提供[eval的json file](https://huggingface.co/datasets/Yongxin-Guo/TRACE/tree/main/eval/dvc/anet)。如果遇到指标很奇怪可以再提供点细节给我

谢谢提供！我先尝试一下这个annotation file，如果有报错我再把报错信息附上，感谢：）

**Comment by WikiChao** [comment]
> 麻烦把报错发一下给我，谢谢

您好，这里是报错信息
<img width="1564" alt="image" src="https://github.com/user-attachments/assets/d673bda2-b47b-4d41-8837-7804d37f2a67" />

input_ids 在 进入 model.evaluate() [evaluate.py] 时是有值的，但是似乎没有被传入llm并初始化成None了

**Comment by gyxxyg** [comment]
这个错误是因为transformers版本太高了，我们改了默认的这个函数所以他更新了以后不适配了

**Comment by WikiChao** [comment]
> 这个错误是因为transformers版本太高了，我们改了默认的这个函数所以他更新了以后不适配了

可以提供一下可行的版本吗

**Comment by gyxxyg** [comment]
可以试试4.40.1

**Comment by WikiChao** [comment]
> 可以试试4.40.1

新的报错出现了，请问有什么解决方案吗

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/e2361683-0f36-41b8-94e7-22a8ae5bc559" />

**Comment by gyxxyg** [comment]
这个我确实没遇到过，方便提供下更多信息吗？

**Comment by WikiChao** [comment]
> 这个我确实没遇到过，方便提供下更多信息吗？

当第二次调用prepare_inputs_labels_for_multimodal函数时，input_ids从 tensor([[32003]], device='cuda:0') 变成了 tensor([[32003, 32003]], device='cuda:0'), 所以下面这两行代码就变成了 tensor([True, True], device='cuda:0') and tensor([True, True], device='cuda:0')， 导致了 RuntimeError: Boolean value of Tensor with more than one value is ambiguous

<img width="568" alt="image" src="https://github.com/user-attachments/assets/b7e66f27-e3ce-4b2a-bdd8-1b9e5a44c420" />

**Comment by gyxxyg** [comment]
按照我的经验，在decoding阶段，[这里](https://github.com/gyxxyg/TRACE/blob/master/trace/model/language_model/trace_mistral.py)调用完`super().prepare_inputs_for_generation`之后，_inputs里面的'input_ids'应该只有一个，可以确认下是不是这里出了问题。

猜测可能是没用kvcache？

**Comment by WikiChao** [comment]
> 按照我的经验，在decoding阶段，[这里](https://github.com/gyxxyg/TRACE/blob/master/trace/model/language_model/trace_mistral.py)调用完`super().prepare_inputs_for_generation`之后，_inputs里面的'input_ids'应该只有一个，可以确认下是不是这里出了问题。
> 
> 猜测可能是没用kvcache？

是这里的问题，调用完`super().prepare_inputs_for_generation`，_inputs里面没有'input_ids'。
kvcache应该已经设为True了(如果是通过use_cache触发）

**Comment by gyxxyg** [comment]
不太可能没有吧，一般来说prefill阶段是直接用的input_embeds所以没用id，但是后面的decoding阶段应该都是有id的，或许再check下？

**Comment by WikiChao** [comment]
> 不太可能没有吧，一般来说prefill阶段是直接用的input_embeds所以没用id，但是后面的decoding阶段应该都是有id的，或许再check下？

check了下，第一次decode没有id但是后面就有了，所以应该这块没有问题。我看了下 [这里](https://github.com/gyxxyg/TRACE/blob/master/trace/model/language_model/trace_mistral.py) 调用完super().prepare_inputs_for_generation之后_inputs里面的'input_ids'的数量是增长的，所有函数中的past_key_values设置也是代码仓库中default的设置。我尝试将_inputs里面的'input_ids'手动设置成最后一个也不行。猜想可能是哪里的config没有设置好，但是提供的`eval.sh`中似乎没有更改相关config的选项。

**Comment by WikiChao** [comment]
> 感觉上可能还是transformers版本不对的样子，不过按理说手动设置成最后一个应该可以，方便看下是什么错误吗？

修改[这行代码](https://github.com/gyxxyg/TRACE/blob/8c48adeb6ab4284a012860c6448e6940068043af/trace/model/trace_arch.py#L350C1-L351C1) 为cur_input_ids = input_ids[batch_idx][-1]，错误信息如下
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/cebb016d-1cd3-4975-8541-e258a946120f" />

另外我会试试不同版本的transformers，希望能解决问题

**Comment by gyxxyg** [comment]
这里应该是少了个维度，不过还是不推荐这样子改。

可以再检查下版本 & 看看kvcache有没有真的使用。

**Comment by WikiChao** [comment]
解决方案：修改[这行代码](https://github.com/gyxxyg/TRACE/blob/8c48adeb6ab4284a012860c6448e6940068043af/trace/model/trace_arch.py#L350C1-L351C1)为`cur_input_ids = input_ids[batch_idx][-1].unsqueeze(0)`。
